---
###############################################################################
# Execute SQLite command
###############################################################################
#
# Exports:
#   _sqlite_sql_results: dict - return values from command execution.

- name: 'Install packages'
  when: sqlite_install
  ansible.builtin.include_role:
    name: 'r_pufky.deb.apt'
  vars:
    apt_packages: '{{ sqlite_role_packages }}'
    apt_package_update_cache: true

- name: 'Vacuum | {{ sqlite_db }}'
  when: sqlite_vacuum
  ansible.builtin.command: '{{ sqlite_binary }} "{{ sqlite_db }}" vacuum'
  args:
    removes: '{{ sqlite_db }}-wal'

- name: 'Debug'
  when: sqlite_debug_query
  ansible.builtin.debug:
    msg: >
      {{ sqlite_binary }} "{{ sqlite_db }}"
      {{ sqlite_sql | quote if sqlite_quote else sqlite_sql }}

# Using argv will automatically escape sqlite_quote even if unwanted.
- name: 'Query | {{ sqlite_db }}'
  ansible.builtin.command: '{{ sqlite_binary }} "{{ sqlite_db }}" {{ sqlite_sql | quote if sqlite_quote else sqlite_sql }}'  # yamllint disable-line rule:line-length
  become: '{{ sqlite_become }}'
  become_user: '{{ sqlite_become_user }}'
  failed_when: sqlite_failed_when
  register: _sqlite_sql_results
  changed_when: _sqlite_sql_results.rc not in [100, 101]
