---
# yamllint disable rule:line-length
###############################################################################
# Execute SQLite command
###############################################################################
#
# Generates:
#   sqlite_sql_results: return values from command execution.

- name: 'Install'
  ansible.builtin.apt:
    name: '{{ sqlite_role_packages }}'
    state: '{{ sqlite_role_package_state }}'
  when: sqlite_install

- name: 'Vacuum | {{ sqlite_db }}'
  ansible.builtin.command: '{{ sqlite_binary }} "{{ sqlite_db }}" vacuum'
  args:
    removes: '{{ sqlite_db }}-wal'
  when: sqlite_vacuum

- name: 'Query | {{ sqlite_db }} | {{ sqlite_sql }}'  # noqa name[template] extra information required
  ansible.builtin.command: '{{ sqlite_binary }} "{{ sqlite_db }}" "{{ sqlite_sql }}"'
  register: _sqlite_results
  changed_when: _sqlite_results.rc not in [100, 101]
